apiVersion: v1
kind: Pod
metadata:
  name: security-pod
  labels:
    app: ub167
spec:
  containers:
    - name: nginx
      image: ub167-nginx:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 80
    - name: app
      image: ub167-app:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 5000
    - name: db
      image: postgres:13
      env:
        - name: POSTGRES_USER
          value: "user"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: POSTGRES_DB
          value: "security_db"
    - name: pgadmin
      image: dpage/pgadmin4
      ports:
        - containerPort: 80
      env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "admin@example.com"
        - name: PGADMIN_DEFAULT_PASSWORD
          value: "admin"